### ISSUE TITLE
Error with follow user

### ISSUE THREAD

**Issue by longisland** [VVX7/Guttr#1]
{'_t': 'xresp', 'rc': 'ERR', 'error': {'_t': 'xerr', 'code': 'E_BAD_TOKEN', 'emsg': 'null', 'args': []}}

**Comment by VVX7** [comment]
Hi @longisland 

Thanks for your interest but I won't be maintaining this project.  The earthlings at stanfordio are conjuring something better https://github.com/stanfordio/gogettr
